language: python
python:
  - "3.6"
before_install:
  - cd ditto_web_api
install:
  - pip install flake8
  - pip install -r requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - flake8 ./DittoWebApi
  - python lint_threshold_check.py ./DittoWebApi
  - pytest ./DittoWebApi
