---  
- name: Install basic dev packages
  yum:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - gcc
    - kernel-devel 
    - kernel-headers 
    - dkms 
    - git
    - lsof
    - zip
    - unzip

- name: Install Software Collections
  yum:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - yum-conf-repos
    - yum-conf-softwarecollections

- name: Search for dev toolset 6
  yum:
    list: devtoolset-6
  register: package_list

- name: Install dev toolset 6
  yum:
    name: devtoolset-6
    state: present
  become: true
  when: 'package_list.results | length != 0'

# install alternatives
- name: Install dev toolset 6 alternatives
  yum:
    name: "{{ packages }}"
    state: present
  become: true
  vars:
    packages:
    - http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-6/devtoolset-6-runtime-6.1-1.el7.x86_64.rpm
    - http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-6/devtoolset-6-binutils-2.27-12.el7.1.x86_64.rpm
    - http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-6/devtoolset-6-binutils-devel-2.27-12.el7.1.x86_64.rpm
    - http://mirror.centos.org/centos/7/sclo/x86_64/rh/devtoolset-6/devtoolset-6-gcc-6.3.1-3.1.el7.x86_64.rpm
  when: 'package_list.results | length == 0'

