Vagrant.configure("2") do |config|
  config.ssh.forward_agent = true
  
  config.vm.define "dittotestbox" do |dittotestbox|
    dittotestbox.vm.box = "gugek/scientific-linux-7"
    dittotestbox.vm.box_version = "7.2.0"
    dittotestbox.vm.network "private_network", ip: "172.28.129.160"
	
	dittotestbox.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
    end
	
	dittotestbox.vm.provision "shell", path: "minio/setup_minio_server.sh"
  end
end
